name: Build and deploy FrontOffice.Api to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: arpce-homologation-frontoffice-api       # <-- your App Service name
  PROJECT_PATH: arpce-homologation-frontOffice/FrontOffice.Api
  PUBLISH_DIR: arpce-homologation-frontOffice/FrontOffice.Api/publish

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{ env.PROJECT_PATH }}

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./publish
        working-directory: ${{ env.PROJECT_PATH }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.PUBLISH_DIR }}
